spring.application.name=veteran-resource-locator

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/veteran_resources
spring.datasource.username=veteran_user
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080